[package]
name = "chess"
version = "0.1.0"
authors = ["marhoily <marhoily@homtail.com>"]

[dependencies]
bitflags = "0.7"
nom = "^1.2.4"
clippy = "0.0.94"
rand = "0.3"
itertools = "0.5.1"
quickcheck = "0.3.1"